var vietnamese = {
	"CloseVideo": "Bấm vào đây để đóng video",
	"VideoHDSD": "Video hướng dẫn sử dụng",
	"CloseFrame": "Đóng",
	"AddQues": "Thêm câu hỏi",
	"Review": "Ôn tập",
	"Feedback": "Góp ý, báo lỗi",
	"InOutData": "Nhập/xuất dữ liệu",
	"InData": "Nhập dữ liệu",
	"PasteDataHere": "Dán dữ liệu đã được sao chép vào đây...",
	"OutData": "Xuất dữ liệu",
	"CopyDataHere": "Sao chép toàn bộ nội dung dưới đây và dán sang thiết bị khác để nhập dữ liệu vào đó",
	"CloseWindow": "Đóng cửa sổ này",
	"NhapCH": "Nhập câu hỏi...",
	"NhapCTL": "Nhập câu trả lời... ",
	'NoteNgoacVuong': 'Lưu ý: <i>Đặt <b>từ khóa cần ghi nhớ</b> trong dấu ngoặc vuông "[]" để ẩn nó. Ví dụ: <b>Hello có nghĩa là [xin chào]</b>, khi đó, từ <b>"xin chào"</b> sẽ bị ẩn</i>',
	"Difficult": "Chọn độ khó của câu này",
	"Easy": "Dễ (1 tuần sau sẽ ôn lại)",
	"Medium": "Trung bình (4 ngày sau sẽ ôn lại)",
	"Hard": "Khó (1 ngày sau sẽ ôn lại)",
	"Save": "Lưu",
	"TotalLearn": "Tổng cộng",
	"NeedLearn": "Cần ôn",
	"HaveLearned": "Đã học",
	"ShowKeyword": "Bấm vào các dải màu xám để hiện thị từ khóa chính bị ẩn",
	"ShowDapAn": "Bấm vào đây để xem đáp án",
	"PauseReview": "Tạm dừng ôn tập (Những gì bạn đã ôn vẫn sẽ được lưu)",
	"CompleteReview": "Đã xong câu này",
	"NothingToReview": "Bạn không còn gì để học hôm nay cả!",
	"Cancel": "Hủy bỏ",
	"DontHaveQues": "Chưa có câu hỏi nào. Bấm vào nút Thêm câu hỏi để thêm câu hỏi mới...",
	"Del": "Xóa",
	"MulDel": "Xóa những câu đã chọn",
	"MulColorMark": "Đánh dấu màu những câu đã chọn",
	"MulTag": "Gắn tag những câu đã chọn",
	"Edit": "Sửa",
	"ShowPreview": "Bấm vào đây để xem những gì sẽ được hiển thị",
	"ChooseLang": "Chọn ngôn ngữ",
	"AUSDel": "Bạn có chắc chắn muốn xóa?",
	"Setting": "Cài đặt",
	"SourceCode": "Xem mã nguồn",
	"PreviewTips": "Nhập nội dung vào ô phía trên để xem trước...",
	"Changelog": "Xem lịch sử sửa đổi",
	"Eng": "Tiếng Anh",
	"NhapTag": "Nhập nhãn...",
	"Action": "Hành động",
	"Search": "Tìm kiếm",
	"SearchInput": "Nhập nội dung tìm kiếm...",
	"SearchType": "Chọn kiểu tìm kiếm",
	"SearchTag": "Tìm theo tag",
	"SearchTitle": "Tìm theo câu hỏi",
	"SearchContent": "Tìm theo nội dung, đáp án",
	"SearchColor": "Tìm theo màu",
	"ColorChon": "Chọn màu muốn tìm...",
	"White": "Trắng",
	"Red": "Đỏ",
	"Orange": "Cam",
	"Yellow": "Vàng",
	"Green": "Lục",
	"Indigo": "Chàm",
	"Violet": "Tím",
	"Blue": "Lam",
	"Pink": "Hồng",
	"Brown": "Nâu",
	"Gray1": "Xám 1",
	"Gray2": "Xám 2",
	"DontHaveQuery": "Không tìm thấy kết quả tương ứng...",
	"tag": "tag",
	"question": "câu hỏi",
	"content": "nội dung",
	"color": "màu",
	"SearchResult": "Kết quả tìm kiếm (",
	"ForQuery": ") cho từ khóa: ",
	"SearchResultColor": "Kết quả tìm theo màu cho màu ",
	"Back": "Quay lại",
	"EnterNTag": "Nhập tag mới",
	"SelectAll": "Chọn tất cả",
	"UnselectAll": "Bỏ chọn tất cả",
	"ChooseFileType": "Chọn kiểu tệp tin",
	"TxtFile": "Tệp văn bản (.txt)",
	"ExcelFile": "Tệp excel (.xls/.xlsx)",
	"Download": "Tải về",
	"Point": "Điểm",
	"point": "điểm",
	"Beginner": "Sơ cấp 1",
	"High beginner": "Sơ cấp 2",
	"Low intermediate": "Tiền trung cấp",
	"Intermediate": "Trung cấp 1",
	"High intermediate": "Trung cấp 2",
	"Low advanced": "Tiền cao cấp",
	"Anvanced": "Cao cấp",
	"Professional": "Chuyên nghiệp",
	"Master": "Bậc thầy",
	"YoureIn": "Cấp độ hiện tại: ",
	"toUpLv": " điểm nữa để lên cấp độ tiếp theo",
	"CongMasterLV": "Chúc mừng, bạn đã là <b>Bậc thầy</b>. <br/>Hãy tiếp tục học nhé!",
	"sentence": "câu",
};

var english = {
	"CloseVideo": "Click here to close video",
	"sentence": "sentence(s)",
	"CongMasterLV": "Congratulations, you are already a <b>Master</b>. <br/>Keep learning!",
	"YoureIn": "Current level: ",
	"toUpLv": " point(s) required for next level",
	"Point": "Point",
	"point": "point(s)",
	"Beginner": "Beginner",
	"High beginner": "High beginner",
	"Low intermediate": "Low intermediate",
	"Intermediate": "Intermediate",
	"High intermediate": "High intermediate",
	"Low advanced": "Low advanced",
	"Anvanced": "Anvanced",
	"Professional": "Professional",
	"Master": "Master",
	"Download": "Download",
	"ChooseFileType": "Choose the file type",
	"TxtFile": "Text file (.txt)",
	"ExcelFile": "Excel file (.xls/.xlsx)",
	"SelectAll": "Select All",
	"UnselectAll": "Unselect All",
	"EnterNTag": "Enter new tag",
	"MulDel": "Delete selected answers",
	"MulColorMark": "Color marking the selected sentences",
	"MulTag": "Tagging selected sentences",
	"Back": "Back",
	"SearchResultColor": "Search results by color for ",
	"SearchResult": "Search results (",
	"ForQuery": ") for keyword: ",
	"DontHaveQuery": "No matching results found...",
	"tag": "Tag",
	"question": "Question",
	"content": "Content, answer",
	"Pink": "Pink",
	"Brown": "Brown",
	"Gray1": "Gray 1",
	"Gray2": "Gray 2",
	"color": "Color",
	"White": "White",
	"Red": "Red",
	"Orange": "Orange",
	"Yellow": "Yellow",
	"Green": "Green",
	"Blue": "Blue",
	"Indigo": "Indigo",
	"Violet": "Violet",
	"ColorChon": "Choose the color...",
	"SearchInput": "Enter search query...",
	"SearchType": "Choose a search type",
	"SearchTag": "Search by tag",
	"SearchTitle": "Search by question",
	"SearchContent": "Search by content, answer",
	"SearchColor": "Search by color",
	"Action": "Action",
	"Search": "Search",
	"NhapTag": "Enter tag...",
	"Eng": "English",
	"Changelog": "View changelog",
	"ShowPreview": "Click here to see what will be displayed",
	"PreviewTips": "Enter the text in the box above to preview...",
	"SourceCode": "View source code",
	"AUSDel": "Are you sure to delete?",
	"Setting": "Setting",
	"ChooseLang": "Choose the language",
	"VideoHDSD": "Video tutorial",
	"CloseFrame": "Close",
	"AddQues": "Add question",
	"Review": "Review",
	"Feedback": "Feedback",
	"InOutData": "Import/Export",
	"InData": "Import data",
	"PasteDataHere": "Paste the copied data here...",
	"OutData": "Export data",
	"CopyDataHere": "Copy the entire content below and paste it into another device to enter data into",
	"CloseWindow": "Close this window",
	"NhapCH": "Enter the question...",
	"NhapCTL": "Enter the answer... ",
	'NoteNgoacVuong': 'Note: <i>Put<b> keywords to remember</b> in square brackets "[]" to hide it. For example: <b>Hello means [xin chào]</b>, then the word <b>"xin chào"</b> will be hidden</i>',
	"Difficult": "Choose the difficulty of this sentence",
	"Easy": "Easy (1 week later will review)",
	"Medium": "Medium (4 days later will review)",
	"Hard": "Hard (1 day later will review)",
	"Save": "Save",
	"TotalLearn": "Total",
	"NeedLearn": "Need to review",
	"HaveLearned": "Have learned",
	"ShowKeyword": "Click on the gray bands to show the hidden main keyword",
	"ShowDapAn": "Click here to show the answer",
	"PauseReview": "Pause review (What you have reviewed will still be saved)",
	"CompleteReview": "Complete",
	"NothingToReview": "You have nothing to learn today!",
	"Cancel": "Cancel",
	"DontHaveQues": "No questions. Click the Add question button to add a new question...",
	"Del": "Del",
	"Edit": "Edit",
};
